version: "3.9"  # Docker-compose 버전

services:
  frontend:
    image: ghcr.io/bandeutseolap/bandeutseolap/frontend:latest
    container_name: bandeutseolap-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks: [mynet]

  backend:
    image: ghcr.io/bandeutseolap/bandeutseolap/backend:latest
    container_name: bandeutseolap-backend
    ports:
      - "8080:8080"
    env_file:
      - ./.backend.env
    environment:
          - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    restart: unless-stopped
    networks: [mynet]

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - /data/redis:/data
      - /logs/redis:/var/log/redis
    restart: unless-stopped
    networks: [ mynet ]

networks:
  mynet:
